<?php

namespace ContainerUZ37RwV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEasyDeploy_Command_RollbackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'easy_deploy.command.rollback' shared service.
     *
     * @return \EasyCorp\Bundle\EasyDeployBundle\Command\RollbackCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easy-deploy-bundle/src/Command/RollbackCommand.php';

        $container->privates['easy_deploy.command.rollback'] = $instance = new \EasyCorp\Bundle\EasyDeployBundle\Command\RollbackCommand((($container->hasParameter("kernel.project_dir")) ? ($container->getParameter("kernel.project_dir")) : (($container->getParameter("kernel.root_dir") . "/.."))), (\dirname(__DIR__, 3).'/log'));

        $instance->setName('rollback');

        return $instance;
    }
}
