<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\PagesController::index'], [], [['text', '/']], [], []],
    'homepage_fr' => [[], ['_controller' => 'App\\Controller\\PagesController::indexfr'], [], [['text', '/fr']], [], []],
    'projects' => [[], ['_controller' => 'App\\Controller\\PagesController::projects'], [], [['text', '/projects']], [], []],
    'projects_fr' => [[], ['_controller' => 'App\\Controller\\PagesController::projectsfr'], [], [['text', '/projects_fr']], [], []],
    'resume' => [[], ['_controller' => 'App\\Controller\\PagesController::resume'], [], [['text', '/resume']], [], []],
    'resume_fr' => [[], ['_controller' => 'App\\Controller\\PagesController::resumefr'], [], [['text', '/resume_fr']], [], []],
];
